exports.projectQuestions = ({
  'Timestamp': 'timestamp',
  '¿Quién eres?': 'user',
  '¿Qué proyecto acabas de terminar?': 'project',
  'Pensando en tu bienestar, ¿crees que podrías sostener el ritmo de este mismo proyecto durante el resto del bootcamp?': 'comfort',
  '¿Por qué comfort?': 'reasonWellBeing',
  'En general, ¿qué tan satisfecha estás con el programa hasta hoy?': 'satisfaction',
  '¿Por qué satisfaction?': 'reasonSatisfaction',
  '¿Sientes que Laboratoria te está preparando para el trabajo desarrollando las habilidades socioemocionales (o "blandas" o "soft skills") necesarias?': 'preparationSoftSkills',
  '¿Sientes que Laboratoria te está preparando para el trabajo con las habilidades técnicas necesarias?': 'preparationTechSkills',
  '¿Sientes que puedes aprender a tu propio ritmo?': 'selfLearning',
  '¿Sientes que logramos hacer que tu experiencia de aprendizaje sea personalizada / individual?': 'customizedLearningExperience',
  '¿Sientes que el equipo cuenta con las habilidades para guiarte adecuadamente en tu aprendizaje?': 'teamSkills',
  '¿Sientes que el equipo tiene la disponibilidad de tiempo para acompañarte y guiarte en tu aprendizaje?': 'availability',
  '¿Sientes que el equipo tiene la predisposición para acompañarte y guiarte en tu aprendizaje?': 'predisposition',
  '¿Por qué predisposition?': 'teamPredisposition',
  '¿Qué mensaje le darías a lxs miembros del equipo para mejorar? Recuerda que el feedback es un regalo :)': 'teamFeedback',
  'Durante este proyecto, ¿alguna vez pensaste en abandonar el programa?': 'dropout',
  '¿Por qué dropout?': 'dropoutChance',
  '¿Quieres comentarnos algo más?': 'comments',
});

exports.sprintQuestions = ({
  'Timestamp': 'timestamp',
  '¿Quién eres?': 'user',
  '¿En qué proyecto estás trabajando?': 'project',
  '¿En qué sprint estás?': 'sprint',
  'En general, ¿cómo te sentiste este Sprint?': 'feeling',
  '¿Por qué te sientes así?': 'reasonFeeling',
  '¿Cuánto sientes que has progresado en tu proyecto en este sprint?': 'progress',
  '¿Cuánto sientes que has aprendido en este sprint?': 'selfLearning',
  'Esta semana, ¿recibiste feedback (retroalimentación) sobre tu trabajo? [De tus coaches]': 'teamFeedback',
  'Esta semana, ¿recibiste feedback (retroalimentación) sobre tu trabajo? [De tus compañeras]': 'peerFeedback',
  '¿Cuántas veces tuviste ayudantías /Office Hours /code review / etc, en este sprint?': 'codeReview',
  '¿Tienes algún otro comentario que dejarnos? Lo puedes dejar aquí :)' : 'comments'
});
